const char* javascript_map_script =
"var map = L.map('map').setView([0, 0], 2); // Başlangıçta dünya merkezine ayarla\n"
"var currentMarker = L.marker([0, 0]).addTo(map); // Her zaman bir işaretçi olsun, başlangıçta 0,0'da\n"
"currentMarker.bindPopup(\"GPS Konumu\").openPopup(); // Başlangıçta bir pop-up olsun\n"
"\n"
"L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\n"
"  maxZoom: 19,\n"
"  attribution: '© OpenStreetMap'\n"
"}).addTo(map);\n"
"\n"
"function updateMap(latitude, longitude) {\n"
"  var latDisplay = 'N/A';\n"
"  var lonDisplay = 'N/A';\n"
"\n"
"  if (!isNaN(latitude) && !isNaN(longitude) && (latitude !== 0 || longitude !== 0)) {\n"
"      var newLatLng = new L.LatLng(latitude, longitude);\n"
"      currentMarker.setLatLng(newLatLng); // İşaretçiyi yeni konuma taşı\n"
"      map.setView(newLatLng, 15); // Haritayı yeni konuma odakla ve zoom yap\n"
"      latDisplay = latitude.toFixed(6);\n"
"      lonDisplay = longitude.toFixed(6);\n"
"  } else {\n"
"      currentMarker.setLatLng(new L.LatLng(0, 0));\n"
"      map.setView([0, 0], 2);\n"
"  }\n"
"  document.getElementById('currentLat').innerText = latDisplay;\n"
"  document.getElementById('currentLon').innerText = lonDisplay;\n"
"}\n"
"\n"
"function fetchGpsDataForMap() {\n"
"  var xhr = new XMLHttpRequest();\n"
"  xhr.onreadystatechange = function() {\n"
"    if (this.readyState == 4 && this.status == 200) {\n"
"      var data = JSON.parse(this.responseText);\n"
"      var lat = parseFloat(data.latitude);\n"
"      var lon = parseFloat(data.longitude);\n"
"      updateMap(lat, lon);\n"
"    }\n"
"  };\n"
"  xhr.open(\"GET\", \"/get_gps_data\", true); // Mevcut GPS veri endpoint'ini kullan\n"
"  xhr.send();\n"
"}\n"
"\n"
"setInterval(fetchGpsDataForMap, 3000); // Her 3 saniyede bir güncelle\n"
"fetchGpsDataForMap(); // Sayfa yüklendiğinde ilk veriyi hemen çek\n"; 